---

- name: Initial setup
  hosts: all

- name: ufw
  import_playbook: ufw.yml

- name: uriparser
  import_playbook: uriparser.yml

- name: resolved
  import_playbook: systemd-resolved.yml

- name: unattended-upgrades
  import_playbook: unattended-upgrades.yml

- name: logrotate
  import_playbook: logrotate.yml

- name: nginx
  import_playbook: nginx.yml

- name: lets-encrypt
  import_playbook: lets-encrypt.yml