#sudo apt install certbot
#sudo certbot register
#chmod 2755 /etc/letsencrypt/live /etc/letsencrypt/archive


#http challenge
#certbot certonly --standalone
#${webroot-path}/.well-known/acme-challenge

#mkdir /var/local/www/testing.reinke.co
#check if domain exists
#certbot certonly -n --webroot -w /var/local/www/testing.reinke.co -d testing.reinke.co
#flush access.log


#mkdir /var/local/www
#chmod

#location /.well-known/acme-challenge/ {
#  root /var/local/www/$host;
#}

