---

- name: Compile Nginx from sources
  hosts: all
  vars:
    nginx_version: nginx-1.15.9
    nginx_tarball_url: "http://nginx.org/download/{{ nginx_version }}.tar.gz"
    nginx_install_dir: "/tmp/{{ nginx_version }}"
    nginx_conf_path: "/etc/nginx/nginx.conf"
    nginx_log_path: "/var/log/nginx"
    nginx_www_path: "/var/local/www"

  tasks:
  
  - name: Installing Nginx Dependencies
    become: yes
    apt:
      name: "{{ item }}"
      update_cache: yes
      autoclean: yes
      autoremove: yes
    with_items:
      - gcc
      - make
      - unzip
      - libssl-dev
      - zlib1g-dev
      - libpcre3-dev
      - libidn2-0-dev

  - name: Downloading Redirector
    get_url:
      url: "https://github.com/carsonreinke/redirector/archive/master.tar.gz"
      dest: "/tmp"
    register: redirector_source

  - name: Directory Redirector
    stat:
      path: /tmp/redirector-master
    register: redirector_source_details

  - name: Unpacking Redirector
    unarchive:
      copy: no
      dest: "/tmp/"
      src: "/tmp/redirector-master.tar.gz"
    register: redirector_source_unpack
    when: redirector_source.changed or redirector_source_details.stat or redirector_source_details.stat.isdir == false

  - name: Downloading Nginx sources
    get_url:
      url: "{{ nginx_tarball_url }}"
      dest: "/tmp/{{ nginx_version }}.tar.gz"
    register: nginx_source

  - name: Unpacking Nginx
    unarchive:
      copy: no
      dest: /tmp/
      src: "{{ nginx_source.dest }}"
    when: nginx_source.changed
    register: nginx_source_unpack

  - name: Create Nginx log directory
    become: yes
    file:
      path: "{{ nginx_log_path }}"
      state: directory
      owner: root
      mode: 0755
  
  - name: Create Nginx www directory
    become: yes
    file:
      path: "{{ nginx_www_path }}"
      state: directory
      owner: root
      mode: 0755

  - name: Configuring Nginx source with custom modules
    command: "./configure --prefix=/usr/local --conf-path={{ nginx_conf_path }} --pid-path=/run/nginx.pid --error-log-path={{ nginx_log_path }}/error.log --http-log-path={{ nginx_log_path }}/access.log --with-http_ssl_module --add-module=/tmp/redirector-master --without-http_access_module --without-http_auth_basic_module --without-http_browser_module --without-http_empty_gif_module --without-http_fastcgi_module --without-http_geo_module --without-http_gzip_module --without-http_limit_conn_module --without-http_limit_req_module --without-http_map_module --without-http_memcached_module --without-http_proxy_module --without-http_referer_module --without-http_scgi_module --without-http_ssi_module --without-http_split_clients_module --without-http_upstream_hash_module --without-http_upstream_ip_hash_module --without-http_upstream_keepalive_module --without-http_upstream_least_conn_module --without-http_upstream_zone_module --without-http_userid_module --without-http_uwsgi_module"
    args:
      chdir: "{{ nginx_install_dir }}"
    register: nginx_configure

  - name: Installing Nginx
    become: yes
    shell: make && make install
    args:
      chdir: "{{ nginx_install_dir }}"

  - name: Creating Nginx conf file
    become: yes
    copy:
      src: "{{ playbook_dir }}/../nginx.conf"
      dest: "{{ nginx_conf_path }}"
      owner: root
      group: root
      mode: 0644

  - name: Installing Nginx systemd service
    become: yes
    copy:
      src: "{{ playbook_dir }}/../nginx.service"
      dest: "/lib/systemd/system/nginx.service"
      owner: root
      group: root
      mode: 0644

  - name: Enable and start Nginx systemd service
    become: yes
    systemd:
      name: nginx
      daemon_reload: yes
      enabled: yes
      state: restarted