---

- name: Setup Unattended Upgrades
  hosts: all
  tasks:

  - name: Update local configuration
    become: yes
    copy:
      src: "{{ playbook_dir }}/../unattended-upgrades.conf"
      dest: "/etc/apt/apt.conf.d/50unattended-upgrades-local"
      owner: root
      group: root
      mode: 0644
  
  - name: Enable and start Unattended Upgrades service
    become: yes
    systemd:
      name: unattended-upgrades
      daemon_reload: yes
      enabled: yes
      state: restarted